### ISSUE TITLE
Please add a code for calculating winding number under twisted boundary condition.

### ISSUE THREAD

**Issue by abdpdn** [K4cp3rski/Topo_SSH#7]
Sorry for asking this as an issue. I really appreciate your work. One more question, will the real space winding number work for diagonal disorder?

**Comment by K4cp3rski** [comment]
Hi! Thank you for kind words 😊 Yes, I think it should, but we haven't tried it yet, since for the time being we went with different disorder definition. If I you have any questions I could help you with, please email me at k.cybinski@student.uw.edu.pl, since for the time being I will be taking the repo private until we finish the project
